name: Publish Docker Image

on:
    push:
        branches:
        - main  
    pull_request:
        branches:
        - main    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Connexion à GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest .

      # Publier sur Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest

      # Publier sur GitHub Container Registry
      - name: Push to GitHub Container Registry
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest ghcr.io/${{ secrets.GITHUBUSERNAME}}/my-node-app:latest
          docker push ghcr.io/${{ github.GITHUBUSERNAME }}/my-node-app:latest
