name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Node.js (même version que dans ton Dockerfile si tu veux tester localement)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'  

      # Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Compiler l’application
      - name: Build application
        run: npm run build

      # Lancer les tests unitaires
      - name: Run tests
        run: npm test
